name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy with scan2html plugin for interactive HTML report
        uses: Fukuro192/trivy-scan2html-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          output: 'trivy-results.html'

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan2html-report
          path: trivy-results.html

      - name: Generate JSON reports for vulnerabilities, misconfigs, and secrets
        run: |
          trivy image --format json --output vulnerabilities.json 'docker.io/my-organization/my-app:${{ github.sha }}'
          trivy config --format json --output misconfigs.json .
          trivy fs --scanners secret --format json --output secrets.json .

      - name: Generate combined interactive HTML report from JSON files
        uses: Fukuro192/trivy-scan2html-action@master
        with:
          scan2html-mode: 'generate'
          scan2html-from: 'vulnerabilities.json,misconfigs.json,secrets.json'
          scan2html-flags: 'true'
          output: 'combined-report.html'

      - name: Upload combined HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-combined-report
          path: combined-report.html
